name: tests
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker
      run: |
        # load the pagila data
        git submodule init
        git submodule update

        # run the database in docker container
        docker-compose up -d --build

        # verify that it is running successfully
        # this is an idempotent command useful for debugging
        docker ps -a

        # after the database starts successfully,
        # it needs time to load the pagila data;
        # this should happen in <1 second,
        # but we sleep for a long time just to be sure that everything is loaded;
        # this is a bit hacky,
        # and a proper check would be to have an infinite loop that terminates once the data has been loaded
        sleep 20

        # run the tests
        docker-compose exec -T pg ./run_tests.sh
